POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "10test@google.com",
  "username": "구글러",
  "password": "googlepass"
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "10test@google.com",
  "password": "googlepass"
}

###
POST http://localhost:8080/users/password_change
Content-Type: application/json

{
  "email": "10test@google.com",
  "newpassword": "awd"
}



###

GET http://localhost:8080/test/test_source
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMHRlc3RAZ29vZ2xlLmNvbSIsImlhdCI6MTc2OTYwNjY3MiwiZXhwIjoxNzY5NjA4NDcyfQ.uzFL74-LBt9P5GYMTDNtYHdrc-99ryZsVAnwtIJlsUw





