POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "1test@google.com",
  "username": "구글러",
  "password": "googlepass"
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "test@google.com",
  "password": "googlepass"
}

###

GET http://localhost:8080/users/me